#!/bin/sh

set -e

c='./sldump --heatmap --json'
o='heatmaps'

[ -e $o ] || mkdir $o

$c > $o/alltime.json &

$c --days   7 >   $o/7days.json
$c --days  70 >  $o/70days.json
$c --days 365 > $o/365days.json

for year in $(seq 2010 $(date +%Y)); do
    $c --period $year > $o/year$year.json
done

wait
